language: node_js
node_js:
- "9"
- "8"
- "7"
- "6"
- "5"
- "4"

install:
    npm install --global mocha

script:
  - export TEST_MODE=TRAVIS
  - export EA_HOSTNAME=$EA_HOSTNAME
  - export EA_ENCRYPTION_KEY=$EA_ENCRYPTION_KEY
  - export EA_TRANSITION_KEY=$EA_TRANSITION_KEY
  - export EA_SALT=$EA_SALT
  - npm install
  - mocha --no-timeouts test/test-url-edgeauth.js
  - mocha --no-timeouts test/test-acl-edgeauth.js